### ISSUE TITLE
Large, high quality qStudio logo?

### ISSUE THREAD

**Issue by richb-hanover** [timeseries/qstudio#113]
To make a sexy logo for the qStudio application, macOS needs a 1024x1024 pixel image that it can reduce down to the appropriate sizes.

Do you have one for qStudio? This obviously could be used for other platforms, for the favicon.ico on the website, etc. Thanks.

**Comment by ryanhamilton** [comment]
Hi Rich, 
The best I have available is: https://www.timestored.com/img/qstudio-180-223.png
In 2013 I think my monitor was 800x600 so it seemed adequate then :)

**Comment by richb-hanover** [comment]
I'll look to see if anyone on Fiverr wants to freelance a larger version of the logo. Should be interesting project (I've never done this before...)

**Comment by ryanhamilton** [comment]
![qstudio-logo](https://github.com/user-attachments/assets/d7fd3f02-c18d-4ef1-8ebe-fbd341169674)
I previously tried to get some of the AI sites to generate an SVG which should be infinitely scalable but they usually had artifacts.

**Comment by richb-hanover** [comment]
@ryanhamilton This is interesting. I see the artifacts, nonetheless I used it to update the application icon for the macOS version. https://randomneuronsfiring.com/wp-content/uploads/qStudio.zip

I'll report back if I get any traction on the Fiverr site...
