### ISSUE TITLE
New key format on newer java versions

### ISSUE THREAD

**Issue by rgoubet** [timeseries/qstudio#15]
![Capture d’écran du 2023-08-15 17-33-49](https://github.com/timeseries/qstudioopen/assets/5311753/af0cae75-7ca1-439f-891a-a23eeb14e79b)

How can I obtain this new key format?

**Comment by ryanhamilton** [comment]
If you email me I will give you a longer key but in case anyone is stuck, this short term new key format should work:

```
QSV3KH4sIAAAAAAAAAGNgYNAz0GESyTkZE5CzaqGu8wql5dZvC55f/mskyCRi2ikc+HePqLyI8jr7+lf
HDqVt/7fXJiczOTWvOFUhvzwvtchWKbUstagyPy/VISuxLNHQXC85P1fJjktBwaagKD+lNLnEB6IcJIQ
QVCjJLMlJtVUqDC4pTcnMV1IoLkksKnFJLAGKGRkYGesaWOgamigYWlgZG1uZWOiZGpophIY4Kymk5qX
AVZmAVVliqoLYBbQtLTWxpLQoFeqEYn2oI/ShrgA7Ux/dnTb6UB/aAQBCLxbMHQEAAA==
```

**Comment by ryanhamilton** [comment]
All keys being issued on TimeStored are now java 17+ compatible.
