### ISSUE TITLE
Updated DuckDB support?

### ISSUE THREAD

**Issue by dmonder** [timeseries/qstudio#19]
When will support for DuckDB 0.9 be included? The 0.5 release of DuckDB was more than 1 year ago.

**Comment by ryanhamilton** [comment]
qStudio 2.53 released just now, includes DuckDB 0.9.2.
I've been testing it for a few days and it works great. 
You will find the new right-click->close connection feature useful if you want to open it back and forth between multiple apps.

The slightly odd thing is you have to change server and then right-click on the unselected duckdb server to close it.
If you left click or try it while active, it may open the connection again. I will need to change that in future.

![image](https://github.com/timeseries/qstudio/assets/7273208/788fc2c9-0a6b-4315-bfea-6ab7811d1c85)

**Comment by dmonder** [comment]
Awesome. Thanks. Just installed it and works great.
