### ISSUE TITLE
qStudio 3.0.2 on macOS gives "Problem sending query to server"

### ISSUE THREAD

**Issue by richb-hanover** [timeseries/qstudio#44]
I'm using qStudio PRO 3.0.2 and Java 16.0.1 on macOS 12.7.5. I have `prqlc` 0.11.3 installed in _/usr/local/bin/prqlc_ which is on my path. When I attempt to run a PRQL query, I see an error message "Problem sending query to server".

Some things are working:

- I opened a SQLite database, made a new query and used Cmd-E to execute `select * from ScrapedData` and the result pane shows the expected results, and the Console shows the correct number of rows.

- prqlc seems to be on the path: `echo 'from employees | filter has_dog | select salary' | prqlc compile` displays the expected SQL commands.

- I opened a new query, and typed a short PRQL query and saved it as _junk.prql_. That worked fine. 

- When I used Query -> Query Current Statement, I get the Problem sending query... message

What other troubleshooting information could I provide? Many thanks for this cool project!

```
√ ~ % java --version
java 16.0.1 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

√ ~ % which prqlc
/usr/local/bin/prqlc

√ ~ % prqlc --version
prqlc 0.11.3

 ~ % echo $PATH
/Users/richb/.local/bin:/Applications/Tools-Developer/Racket:/Users/richb/.pyenv/shims:/Users/richb/.pyenv/bin:/Users/richb/.deno/bin:/Users/richb/.pyenv/bin:/Users/richb/.nvm/versions/node/v20.9.0/bin:/Users/richb/.cargo/bin:/opt/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Apple/bin:/usr/libexec:/Applications/Tools-Developer/Racket/bin:/Users/richb/.rvm/bin

√ ~ % echo 'from employees | filter has_dog | select salary' | prqlc compile
SELECT
  salary
FROM
  employees
WHERE
  has_dog

-- Generated by PRQL compiler version:0.11.3 (https://prql-lang.org)
```

**Comment by ryanhamilton** [comment]
Thanks Rich this is an excellent bug report. (Terrible bug!)

I've going to add better error reporting (image below) and investigate mac now.

![image](https://github.com/timeseries/qstudio/assets/7273208/a989f348-bd91-4016-8c0d-3a1c937242d2)

**Comment by ryanhamilton** [comment]
Display any PRQL errors:
![image](https://github.com/timeseries/qstudio/assets/7273208/425d73e3-c7b2-41bd-8ee0-f70d30db9771)

**Comment by ryanhamilton** [comment]
Released fix in 3.03: https://www.timestored.com/qstudio/download 
@richb-hanover  Please confirm it works for you

**Comment by richb-hanover** [comment]
Thanks for the speedy turnaround. Using 3.03, I get this message:

`java.io.IOException: Cannot run program "prqlc": error=2, No such file or directory`

<img width="739" alt="image" src="https://github.com/timeseries/qstudio/assets/1094930/8fed5c96-e9c6-4c01-8eee-75107d2755ce">

FYI: I don't know if it matters, but I used this procedure to download and run 3.03:
- Download from site to get _qstudio(2).jar_ in _Downloads_
- Double-click it. Mac says no - unknown developer.
- Open System Preferences, Security, click Open Anyway
- Double-click _qstudio(2).jar_ again. Get another security prompt, click Open
- qStudio 3.03 opens as expected. 

PS I like that you remember the previous set of servers/open files/etc. I can just pick up where I left off...

**Comment by ryanhamilton** [comment]
That procedure looks correct, though I will need to look into making it nicer. Thanks for letting me know.

That error seems to suggest prqlc is not on your path. It looks the same as the error I had when I purposefully renamed prqlc. 
Can you try launching qstudio from the terminal:

1. Go to the directory with qstudio.jar
2. Run "prqlc" to make sure it's available.
3. Then run "java -jar qstudio.jar". This should mean it gets launched with the same PATH settings.

If this fails let's either have a zoom call when suits you OR I will add PATH logging to the log output.

**Comment by richb-hanover** [comment]
@ryanhamilton Good news. Your hint suggesting `run -jar qstudio.jar` seems to have broken things free. Things are working after I tweaked/adjusted a ton of things.

I am closing this report, and will write up another set of other observations/questions. THANK YOU!

**Comment by ryanhamilton** [comment]
Brilliant, glad it worked!
Though I'm going to look at improving the mac experience soon.
