### ISSUE TITLE
Renaming `qstudio.jar` - odd behavior

### ISSUE THREAD

**Issue by richb-hanover** [timeseries/qstudio#46]
I downloaded qStudio for Linux/Mac (3.03) and moved it to _/Applications/qStudio_ on my Mac.

I renamed it to _qStudio-3.03.jar_ then issued:

`java -jar qStudio-3.03.jar` 

and I was unable to open a SQLite database that was in the same directory. Is this expected? Is qStudio sensitive to the name of its .jar file? Or could I be doing something wrong? Thanks.

**Comment by ryanhamilton** [comment]
There should be no change in behaviour based on name.
I've now added logging as you suggested to capture the current directory to allow debugging thi sbetter in future.
