### ISSUE TITLE
Fussy (non-harmful) comments on qStudio appearance

### ISSUE THREAD

**Issue by richb-hanover** [timeseries/qstudio#61]
In parallel with #54, I offer these fussy suggestions (I was running qStudio 3.05 from 4Jun2024). I attach a video that demonstrates what I am speaking about. None of these inhibit the proper operation of qStudio, but fixing them would improve the overall "fit and finish" of the program.

- qStudio goes to some lengths to remember the files and servers that were open when it last closed. (This is GREAT! It means that I can launch it and pick up where I left off.) However, it seems that qStudio always fills the screen with its window when it starts. I think it would be better to remember my choice of window size and position when it exits, and restore them when it starts again.
- I'm running on a Mac, so the path in the title bar of the window should use "/" not "\\"
- Also on a Mac - the Result pane suggests that I should use "Ctrl-P"  - on a Mac, I have to use Cmd-P
- At the beginning of the video, I was looking for a menu command that does the same thing as "Ctrl-P". Is there one? Maybe there should be - "Open Command Bar... ^P (or ⌘-P)"
- (Note the ⌘ key is called the "Place of Interest" character on a Mac. Hit Cmd-Ctl-Space to open the emoji picker, type 'Place of' and you'll see it.)
- Finally, I gave up the search and hit Cmd-P. The window of interesting commands popped up. I see:
   - A list of commands that provide alternatives to using the menus. COOL!
   - Some of _my_ recent choices, so I can open a previously opened file from the window. COOL!
   - BUT... some are files that I do NOT recognize. Where did they come from? Previous invocation on a developer machine? I don't envision they should carry to a new machine.

Thanks as always

Here's the video: https://youtu.be/dMOD75AuLpc

™£¡•

**Comment by ryanhamilton** [comment]
- Restoring size / position = done. Will be released in >3.05. I know this will bring complains from multi-monitor users as it's very difficult to restore in those cases.
- Cmd+P I've fixed in the toolbar. Fixing the ResultPanel I'm skipping for now as that text doesn't currently contain code.
- Did you ever use the "File Tree" or File->"Open Folder" ? 
That's often where files will appear from. You can use File->Close Folder to stop those links.


![image](https://github.com/timeseries/qstudio/assets/7273208/191fe8a9-e88a-4520-bd2d-94aad67eeee5)

![image](https://github.com/timeseries/qstudio/assets/7273208/9b2ae188-b894-4691-9a1a-0f1999df9f34)

**Comment by ryanhamilton** [comment]
And thanks for these @richb-hanover , It's useful to know. 
There will always be UI preferences and personal opinions but I should be able to justify choices. 👍 

Oh and the / vs \ I can't easily change. Forward / slash is when it's in a folder:

![image](https://github.com/timeseries/qstudio/assets/7273208/6279e1a5-91c2-48f1-a804-d3bed3da9715)

**Comment by richb-hanover** [comment]
Thanks for the speedy response to so many of these comments. 

I need to state that you should read my comments understanding my standard proviso: "These are things that I notice. I'm just one guy: if I'm the only one in the world to report it, then you should use your judgement about whether to make a change. If lots of people report it, you should _still_ use your judgement." Thanks again.

**Comment by ryanhamilton** [comment]
Ha you described my policy better than I could :)
