### ISSUE TITLE
New "elevator speech" for qStudio

### ISSUE THREAD

**Issue by richb-hanover** [timeseries/qstudio#66]
I have been glibly modifying your "elevator speech" for qStudio. I think it captures the essence of qStudio, and avoids hyperbole. Here's what I used in the PR over on the PRQL site: https://github.com/PRQL/prql/pull/4547

> qStudio is a SQL GUI that lets you browse tables, run SQL scripts, and chart and export the results. qStudio runs on Windows, macOS and Linux, and works with every popular database including mysql, postgresql, mssql, kdb….

But feel free to re-write - I'll update the PRQL site as needed, and you can update the qStudio home page and CHANGELOG.

**Comment by ryanhamilton** [comment]
Perfect, thanks. I'm eagerly awaiting users trying it. Never know similar to sqlite/REGEX, it may surface issues in places we wouldn't have guessed.
