### ISSUE TITLE
"Open file..." should remember previous directory

### ISSUE THREAD

**Issue by richb-hanover** [timeseries/qstudio#83]
Using "Open file..." (Cmd-O on macOS), qStudio always seems to start at the user's home directory.

This is reasonable default behavior when the program is first opened, but highly annoying when opening another file that's nearby, but buried multiple directories down.

Two suggestions:

1. qStudio could return to the directory that contained the previous file on the next "Open file..."

2. qStudio could use the native file picker for the underlying operating system. This would allow straightforward, familiar navigation, and allow people to take advantage of any "file picker enhancements" they have installed. 

Thanks

**Comment by ryanhamilton** [comment]
Strange, the logic to use last folder has been there for a long time:
https://github.com/timeseries/qstudio/blob/master/tscore/src/main/java/com/timestored/docs/DocumentActions.java#L418
I tested just now on windows and ubuntu, both it worked as expected.
Please can you double check?

**Comment by richb-hanover** [comment]
I can confirm that 3.07 _does_ return to the last opened directory, as desired. I don't know why my earlier test didn't show that.

I still would be delighted to have a native file picker, even if qStudio needed to support multiple - different one for one platform. (But I ain't gonna write the code... :-) Thanks again
