### ISSUE TITLE
[SOLVED] "Copy with headers" for Result window

### ISSUE THREAD

**Issue by richb-hanover** [timeseries/qstudio#84]
It's extremely convenient that I can use qStudio to Select All / Copy the contents of the Results window, then paste them into a spreadsheet.

It would be even more convenient if there were a "Copy with headers" facility that copied the header row along with whatever was selected from the Result window. I have seen this elsewhere in [DB Browser for SQLite](https://sqlitebrowser.org/). Its pane that displays the results has a right-click option to "Copy with Headers". See screenshot below. 

Alternatively, perhaps "Select All" could include the headers as part of the selection, either by default, or as a result of some kind of "super-select-all" keyboard shortcut

Thanks

**DB Browser for SQLite - Copy with Headers from right-click  or control-click**
<img width="355" alt="image" src="https://github.com/user-attachments/assets/b1c00d01-92fc-47f4-8934-06d75393e177">

**Comment by ryanhamilton** [comment]
Hi Rich

I think this is already done?

1. If you right click on the result it should allow export of the visible data (It's limited to visible data for legacy reasons).
2. The result component has an excel and email icon that exports the full result even if there are too many rows to be visible.

![image](https://github.com/user-attachments/assets/8bff517d-adee-43f0-a812-09746740eb94)

**Comment by richb-hanover** [comment]
@ryanhamilton This is absolutely solved, and extremely well. It raises a question about documentation - how can a rando like me learn about the feature? THANKS!
