### ISSUE TITLE
Crash installing 3.07 on Win10 and Win11

### ISSUE THREAD

**Issue by richb-hanover** [timeseries/qstudio#85]
I have been using qStudio on macOS, but thought I would compare the experience on Win10 or Win11.

I downloaded the 65Mbyte Installer for Windows, ran it as usual. I had the "open the program" box checked, so qStudio opened a window requesting my email address. (This was hidden behind some other window - I had to seek it out).

I entered it, and a web browser window opened, showing my license key. I ultimately figured out that I should copy this and paste it into the qStudio window. The splash screen appeared, stating that qStudio was licensed to my email and that it was version 3.07. It then crashed, and sent me to the "bug report" web page where I entered my contact info: the stack trace was provided automatically. I had to use the Task Manager to close that frozen qStudio splash screen.

As I say, I have never installed the Windows version before, and it happened on both Win10 and Win11

**Comment by ryanhamilton** [comment]
That is extremely embarassing and I'm glad you raised it ASAP. 
I hadn't tested a scenario where someone had zero servers created and yes it fails to launch.

Corrective Measures:
1. I've reverted the website to 3.06 for now 
2. I'm going to write up the manual tests performed on each release.
3. I'm going to publicly post the testing evidence as an issue for each release.

**Comment by ryanhamilton** [comment]
2. Added https://github.com/timeseries/qstudio/blob/master/DEVTESTING.md

**Comment by richb-hanover** [comment]
I'm happy to help (see my blog post [WPNTFIIWDKIB](https://randomneuronsfiring.com/wpntfiiwdkib/))

**Comment by richb-hanover** [comment]
@ryanhamilton One last question: Is there any trick to uninstalling the 3.07 version on those Win10 and Win11 computers so that I'm back to a "virgin test situation"? Thanks

**Comment by ryanhamilton** [comment]
Running any installer from version 2/3 will overwrite whatever version you have installed.
3.10 is now on the website and can be installed over the old release fine.

**Comment by ryanhamilton** [comment]
3. Test evidence for 3.10 posted. 
https://github.com/timeseries/qstudio/issues/87
Including resetting to have zero servers etc. which was what caused your startup bug. Closing this issue.

**Comment by richb-hanover** [comment]
@ryanhamilton I can confirm that 3.10 installed without issues on Win11. I'll test further and send any comments in a separate issue. Thanks for the speedy response!
